# SPDX-License-Identifier: GPL-2.0+

# Grab our configured image.  The source for this is found at:
image: dockerregistry.emtrion.de/emtrion/debian-crossbuildtoolchain:0.4

stages:
  - u-boot-build

u-boot-build-job:
  stage: u-boot-build
  # select/use only runners marked with the tag "docker" to show that the runner is configured with the executor "docker"
  tags:
    - docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never
  script:
    - uname -a
    - pwd
    - git status
    - git log -n 1
    - export ARCH=armhf
    - export CROSS_COMPILE=arm-linux-gnueabihf-
    - make distclean
    - make emsbc-argon_defconfig
    - make -j 8 -s --print-directory all
    - ls -la u-boo*
  artifacts:
    paths:
      - u-boot
      - u-boot.bin
      - u-boot.stm32
    expire_in: 1 week
